import { getFileExtension, getFileName } from '../../utils/fileUtils';
import type { TreeSitterLanguageId } from '../../utils/treeSitterLanguages';

// Diff metadata: use generic language names (e.g. tsx -> typescript) for snapshots/comments.
const DIFF_EXTENSION_LANGUAGE_MAP: Record<string, string> = {
  js: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  jsx: 'javascript',
  ts: 'typescript',
  mts: 'typescript',
  cts: 'typescript',
  tsx: 'typescript',
  py: 'python',
  rb: 'ruby',
  go: 'go',
  rs: 'rust',
  java: 'java',
  cc: 'cpp',
  cu: 'cpp',
  cuh: 'cpp',
  cpp: 'cpp',
  cxx: 'cpp',
  h: 'cpp',
  hh: 'cpp',
  hpp: 'cpp',
  hxx: 'cpp',
  c: 'c',
  cs: 'csharp',
  php: 'php',
  swift: 'swift',
  kt: 'kotlin',
  scala: 'scala',
  r: 'r',
  sql: 'sql',
  sh: 'bash',
  bash: 'bash',
  zsh: 'bash',
  fish: 'bash',
  yml: 'yaml',
  yaml: 'yaml',
  json: 'json',
  xml: 'xml',
  html: 'html',
  vue: 'html',
  css: 'css',
  scss: 'scss',
  sass: 'sass',
  less: 'less',
  md: 'markdown',
  markdown: 'markdown',
  tex: 'latex',
  vim: 'vim',
  ex: 'elixir',
  exs: 'elixir',
  heex: 'elixir',
  nix: 'nix',
  hs: 'haskell',
  lhs: 'haskell',
  clj: 'clojure',
  cljs: 'clojure',
  cljc: 'clojure',
  edn: 'clojure',
  gd: 'gdscript',
  groovy: 'groovy',
  gvy: 'groovy',
  gy: 'groovy',
  gsh: 'groovy',
  gradle: 'groovy',
};

// Prism syntax highlighting: use Prism language IDs (e.g. tsx -> tsx, scss -> css).
const PRISM_EXTENSION_LANGUAGE_MAP: Record<string, string> = {
  ts: 'typescript',
  tsx: 'tsx',
  mts: 'typescript',
  cts: 'typescript',
  js: 'javascript',
  jsx: 'jsx',
  mjs: 'javascript',
  cjs: 'javascript',
  json: 'json',
  css: 'css',
  scss: 'css',
  html: 'html',
  vue: 'html',
  sh: 'bash',
  bash: 'bash',
  zsh: 'bash',
  fish: 'bash',
  yml: 'yaml',
  yaml: 'yaml',
  md: 'markdown',
  py: 'python',
  rb: 'ruby',
  go: 'go',
  rs: 'rust',
  java: 'java',
  cc: 'cpp',
  cu: 'cpp',
  cuh: 'cpp',
  cpp: 'cpp',
  cxx: 'cpp',
  h: 'cpp',
  hh: 'cpp',
  hpp: 'cpp',
  hxx: 'cpp',
  c: 'c',
  php: 'php',
  sql: 'sql',
  xml: 'xml',
  swift: 'swift',
  kt: 'kotlin',
  scala: 'scala',
  svelte: 'svelte',
  r: 'r',
  lua: 'lua',
  perl: 'perl',
  pl: 'perl',
  pm: 'perl',
  dockerfile: 'docker',
  makefile: 'makefile',
  gitignore: 'git',
  env: 'bash',
  conf: 'nginx',
  ini: 'ini',
  toml: 'toml',
  sol: 'solidity',
  vim: 'vim',
  dart: 'dart',
  cs: 'csharp',
  proto: 'protobuf',
  tf: 'hcl',
  tfvars: 'hcl',
  hcl: 'hcl',
  ex: 'elixir',
  exs: 'elixir',
  heex: 'elixir',
  nix: 'nix',
  hs: 'haskell',
  lhs: 'haskell',
  clj: 'clojure',
  cljs: 'clojure',
  cljc: 'clojure',
  edn: 'clojure',
  gd: 'gdscript',
  groovy: 'groovy',
  gvy: 'groovy',
  gy: 'groovy',
  gsh: 'groovy',
  gradle: 'groovy',
};

const PRISM_FILENAME_LANGUAGE_MAP: Record<string, string> = {
  dockerfile: 'docker',
  makefile: 'makefile',
  '.gitignore': 'git',
  '.env': 'bash',
  '.bashrc': 'bash',
  '.zshrc': 'bash',
  '.bash_profile': 'bash',
  '.profile': 'bash',
};

function getLanguageFromExtension<T extends string>(
  extension: string | null,
  map: Record<string, T>,
): T | undefined {
  if (!extension) return undefined;
  return map[extension.toLowerCase()];
}

export function getLanguageFromPath(filePath: string): string | undefined {
  return getLanguageFromExtension(getFileExtension(filePath), DIFF_EXTENSION_LANGUAGE_MAP);
}

export function getPrismLanguageFromFilename(filename: string): string {
  const basename = getFileName(filename).toLowerCase();
  const special = PRISM_FILENAME_LANGUAGE_MAP[basename];
  if (special) return special;
  return (
    getLanguageFromExtension(getFileExtension(filename), PRISM_EXTENSION_LANGUAGE_MAP) || 'text'
  );
}

const TREE_SITTER_EXTENSION_LANGUAGE_MAP: Record<string, TreeSitterLanguageId> = {
  astro: 'astro',
  bash: 'bash',
  c: 'c',
  cjs: 'javascript',
  clj: 'clojure',
  cljc: 'clojure',
  cljs: 'clojure',
  cc: 'cpp',
  cpp: 'cpp',
  cxx: 'cpp',
  cu: 'cuda',
  cuh: 'cuda',
  cs: 'c_sharp',
  css: 'css',
  cts: 'typescript',
  dart: 'dart',
  ex: 'elixir',
  exs: 'elixir',
  gd: 'gdscript',
  go: 'go',
  gradle: 'groovy',
  groovy: 'groovy',
  gsh: 'groovy',
  gvy: 'groovy',
  gy: 'groovy',
  hcl: 'hcl',
  heex: 'elixir',
  hs: 'haskell',
  html: 'html',
  h: 'cpp',
  hh: 'cpp',
  hpp: 'cpp',
  hxx: 'cpp',
  ini: 'ini',
  java: 'java',
  js: 'javascript',
  json: 'json',
  jsx: 'tsx',
  kt: 'kotlin',
  lua: 'lua',
  mjs: 'javascript',
  mts: 'typescript',
  nix: 'nix',
  perl: 'perl',
  php: 'php',
  pl: 'perl',
  pm: 'perl',
  proto: 'proto',
  py: 'python',
  r: 'r',
  rb: 'ruby',
  rs: 'rust',
  scala: 'scala',
  scss: 'scss',
  sh: 'bash',
  sol: 'solidity',
  sql: 'sql',
  svelte: 'svelte',
  swift: 'swift',
  tf: 'hcl',
  tfvars: 'hcl',
  toml: 'toml',
  ts: 'typescript',
  tsx: 'tsx',
  vim: 'vim',
  vue: 'vue',
  xml: 'xml',
  yaml: 'yaml',
  yml: 'yaml',
  zsh: 'bash',
};

const TREE_SITTER_FILENAME_LANGUAGE_MAP: Record<string, TreeSitterLanguageId> = {
  '.bash_profile': 'bash',
  '.bashrc': 'bash',
  '.env': 'bash',
  '.profile': 'bash',
  '.zshrc': 'bash',
  dockerfile: 'dockerfile',
  makefile: 'make',
};

/**
 * Returns the Tree-sitter grammar used to parse a complete diff-side blob.
 * Undefined means that the line renderer should retain its Prism fallback.
 */
export function getTreeSitterLanguageFromFilename(
  filename: string,
): TreeSitterLanguageId | undefined {
  const basename = getFileName(filename).toLowerCase();
  return (
    TREE_SITTER_FILENAME_LANGUAGE_MAP[basename] ??
    getLanguageFromExtension(getFileExtension(filename), TREE_SITTER_EXTENSION_LANGUAGE_MAP)
  );
}
